### ISSUE TITLE
现在分页at com.jn.easyjson.core.exclusion.ExclusionConfiguration.isExcludedField报空指针

### ISSUE THREAD

**Issue by zwllxs** [fangjinuo/sqlhelper#129]
java.lang.NullPointerException: null
	at com.jn.easyjson.core.exclusion.ExclusionConfiguration.isExcludedField(ExclusionConfiguration.java:110)
	at com.jn.easyjson.fastjson.ext.EasyJsonSerializeConfig.createJavaBeanSerializer(EasyJsonSerializeConfig.java:50)
	at com.alibaba.fastjson.serializer.SerializeConfig.createJavaBeanSerializer(SerializeConfig.java:118)
	at com.alibaba.fastjson.serializer.SerializeConfig.getObjectWriter(SerializeConfig.java:776)
	at com.alibaba.fastjson.serializer.SerializeConfig.getObjectWriter(SerializeConfig.java:430)
	at com.alibaba.fastjson.serializer.JSONSerializer.getObjectWriter(JSONSerializer.java:410)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:282)
	at com.jn.easyjson.fastjson.FastJsonAdapter.serialize(FastJsonAdapter.java:50)
	at com.jn.easyjson.core.JSON.toJson(JSON.java:51)
	at com.jn.easyjson.core.JSON.toJson(JSON.java:39)
	at com.jn.sqlhelper.dialect.pagination.PagingRequest.toString(PagingRequest.java:217)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at com.test.controller.TestController.testPage(TestController.java:65)
![图片](https://user-images.githubusercontent.com/5228810/80228341-834d3600-8681-11ea-8623-a3ad317c7eb9.png)

**Comment by fangjinuo** [comment]
升级 easyjson 到 2.2.1 版本即可

**Comment by fangjinuo** [comment]
@zwllxs 若发现问题解决，可以回复一下，我就可以关闭问题了，o(*￣︶￣*)o

**Comment by zwllxs** [comment]
嗯，升级到指定版本后，本bug已消失了。
