### ISSUE TITLE
MyBatis-Plus能升级到3.3.x以上吗？

### ISSUE THREAD

**Issue by ducp123** [fangjinuo/sqlhelper#146]
MyBatis-Plus能升级到3.3.x以上吗？
官方现在已经到3.4.0了，有些字段和注解做了很大变更呢。

**Comment by fangjinuo** [comment]
理论上讲， mybatis-plus 完全可以自己升级的，把sqlhelper-mybatis里的mybatis-plus依赖排除后，加上新版的mybatis-plus即可

**Comment by yuan50697105** [comment]
更新之后有问题
![Uploading 微信截图_20201021150627.png…]()

**Comment by fangjinuo** [comment]
> 更新之后有问题

图片看不到，你加入到QQ群里说吧

**Comment by yuan50697105** [comment]
更新之后有问题
Connected to the target VM, address: '127.0.0.1:60042', transport: 'socket'
08:06:35.564 [restartedMain] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.NoSuchMethodError: com.baomidou.mybatisplus.core.toolkit.StringUtils.isNotBlank(Ljava/lang/CharSequence;)Z
	at com.baomidou.mybatisplus.autoconfigure.SafetyEncryptProcessor.postProcessEnvironment(SafetyEncryptProcessor.java:55) ~[mybatis-plus-boot-starter-3.4.0.jar:3.4.0]
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:200) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:188) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127) ~[spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:80) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345) [spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) [spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at com.example.java.apps.shower.admin.ShowerAdminApplication.main(ShowerAdminApplication.java:15) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-2.3.4.RELEASE.jar:2.3.4.RELEASE]
Disconnected from the target VM, address: '127.0.0.1:60042', transport: 'socket'

**Comment by fangjinuo** [comment]
你只要保证你引入的mybatis和mybatis-plus版本是兼容的，就应该没有问题的

**Comment by fangjinuo** [comment]
升级到 sqlhelper 3.2.4 即可解决该问题。

【问题原因】
mybatis-plus 自身提供的多个API 出现了版本间不兼容的现象。

【解决方案】
弃用mybatis-plus中在各个版本间不兼容的API。
