### ISSUE TITLE
Supports NamedParameterJdbcTemplate

### ISSUE THREAD

**Issue by netboy33** [fangjinuo/sqlhelper#84]
希望支持NamedParameterJdbcTemplate

**Comment by fangjinuo** [comment]
Supports it at 19ae51f61abe1667d302c883e1eb8ee081aa8094

**Comment by netboy33** [comment]
> Supports it at [19ae51f](https://github.com/fangjinuo/sqlhelper/commit/19ae51f61abe1667d302c883e1eb8ee081aa8094)

Hive分页查询报错，异常堆栈如下：
Caused by: java.sql.SQLFeatureNotSupportedException: Method not supported
	at org.apache.hive.jdbc.HiveBaseResultSet.first(HiveBaseResultSet.java:110)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.first(HikariProxyResultSet.java)
	at com.jn.sqlhelper.springjdbc.JdbcTemplate$2.extractData(JdbcTemplate.java:253)
	at com.jn.sqlhelper.springjdbc.JdbcTemplate$2.extractData(JdbcTemplate.java:250)
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:678)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:616)
	... 38 more

**Comment by netboy33** [comment]
It's OK at f8edc2f
